import { Head, Html, Main, NextScript } from 'next/document';

export default function Document()
{
  return (
    <Html lang="en" className='bg-gray-500'>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content='Generated by create next app' />
        <link rel="icon" href="/favicon.ico" />
        {/* <link rel="stylesheet" href="../styles/globals.css" /> */ }
        <title> Help Africa </title>
      </Head>
      <body className='bg-indigo-500'>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
