import { Head, Html, Main, NextScript } from 'next/document';


export default function Document()
{
  return (
    <Html lang="en" className='dark:bg-slate-900'>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content='Generated by create next app' />
        <link rel="icon" href="/favicon.ico" />
        <title> Help Africa </title>

      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
