import Head from 'next/head';

export default function Home() {
  return (
    <>

      <Head>
        <meta name="description" content='Generated by create next app' />
        <title> Help Africa - Homepage </title>
      </Head>

      {/* HTML CONTENT MAIN TAG */ }
      <main>
        <h1>Help Africa Homepage</h1>
      </main>
    </>
  )
}
